# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Tien Xuan Vo
title: Senior PHP Developer
email: tien.xuan.vo@gmail.com
website: https://tienvx.github.io/

# Social links
twitter_username: tienvoxuan
github_username:  tienvx
# dribbble_username: jekyll
facebook_username: tien.voxuan
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: tienxuanvo
pinterest_username: tienxuanvo
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Tien and I'm a senior PHP developer with over 6 years experience. I am currently working for GO1 as a full stack developer on an e-learning platform.

  I love learning new things by working on new projects. I am most skilled in:
  <mark>ES5 &amp; ES 6 Javascript</mark>,
  <mark>React</mark>,
  <mark>PHP</mark>,
  <mark>MySQL</mark>,
  <mark>Symfony</mark>,
  <mark>Elasticsearch</mark>,
  <mark>AngularJS</mark>,
  <mark>git</mark> and
  <mark>Docker</mark>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
